#DATABASE
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ogani
    username: root
    password: 240301
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      format_sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en

#API
api:
  prefix: api/v1

#JWT
jwt:
  jwtSecret: tuynptit
  jwtExpirationMs: 86400
  jwtCookieName: Bearer

